### ISSUE TITLE
Confused with v4

### ISSUE THREAD

**Issue by shl213** [HPCE/hpce-2017-cw3#23]
I believe in v3 

`cl::Event evCopiedState;
queue.enqueueWriteBuffer(buffState, CL_FALSE, 0, cbBuffer, &world.state[0], NULL, &evCopiedState);`

was written to go within the loop, but I have figured that the pseudo code for overall implementation in v4 shows that this part should go out of the loop. 

Does it make no difference? or Am I suppose to take this out of the loop?

**Comment by m8pple** [comment]
Yes, this should be outside of the loop.

The idea is that you only need to copy the input data to the GPU once (before the loop),
then copy it back from the GPU once (after the loop).

**Comment by SantiagoRubioDev** [comment]
For V4. My code looks like the pseudo code in the spec. It compiles without any errors but when I run it I get:
`Exception : clEnqueueReadBuffer`
It does not say anything else. Did anyone have a similar issue?
My enqueueReadBuffer looks like:
`queue.enqueueReadBuffer(buffBuffer, CL_TRUE, 0, cbBuffer, &world.state[0], &copyBackDependencies);`
Also I am a bit confused to what happens with the line:
`world.t += dt;`
It is not in the V4 pseudo code, does that mean we remove it? If so do we have to put it somewhere else?

**Comment by m8pple** [comment]
The `world.t += dt;` should remain - the pseudo-code is just giving the high-level structure.

(Though due to a bug in the IO code I think `t` is not currently persisted).

As for the exception - have you tried checking the exception code? The
enhanced error checking contributed for [test_opencl.cpp](https://github.com/HPCE/hpce-2016-cw3/blob/master/src/test_opencl.cpp#L121-L131) shows how you
can extract the precise error (it will require some modifications of the
main function).
