### ISSUE TITLE
Does not work using OpenCL 2

### ISSUE THREAD

**Issue by patengelbert** [HPCE/hpce-2017-cw3#26]
On Debian 16.04, the default install grabs OpenCL-headers 2.0.
This does not seem to be backwards compatible with the expected version of OpenCL 1.2.

This will mean that the test code will refuse to compile on any system that runs Ubuntu 16.04 or has manually installed OpenCL 2.0 or higher.

Edit:
This will also be the case for anyone installing the AMD APP SDK v3.0 from the internet as that is built for OpenCL 2.0 as well

**Comment by m8pple** [comment]
Thanks for raising this.

I don't immediately know how to deal with this - the examples use the older
versions because NVidia (at least as far as I can tell), still refuses to move beyond
OpenCL 1.2. As a consequence, to the best of my knowledge there is no
OpenCL 2 driver for the AWS parts (which are NVidia), so we're a bit stuck.

Previously this hasn't been a problem, as the other vendors weren't deploying
OCL2 by default, but now they (quite reasonably) are.

I'll look and see if I can come up with something that is compatible between
OCL1.2 and OCL2 (I think we now no longer need to worry about OCL1.0
and OCL1.1 support), but probably not within the timeframe of this coursework.
