### ISSUE TITLE
AWS AMI

### ISSUE THREAD

**Issue by anferbui** [HPCE/hpce-2017-cw3#3]
Hi,

I'm trying to use AWS but I can't manage to find the image you're referring to in the README, HPCE-2015-GPU-Image. Is that under 'Community AMIs', or do I find it a different way?

I also attempted to reproduce it but I couldn't find the image 'debian-jessie-amd64-hvm-2014-12-25-13-19-ebs (ami-aae18fc2)' either.

There is an AMI 'debian-jessie-amd64-hvm-2015-06-07-12-27-ebs (ami-116d857a)' available, I assume this image will work too?

**Comment by anferbui** [comment]
Anyone wanting to use AWS should use AWSEducate... here's the link:
http://aws.amazon.com/es/education/awseducate/apply/

**Comment by m8pple** [comment]
For the missing HPCE AMI. It looks like I cloned it to the "Oregon" availability zone for some
reason, while "North Virginia" is the default when you log in. I've copied it over, so it should
appear in the default availability zone in a few minutes (~12:40 on Friday). There is also
an image from last year called HPCE-2014-GPU-Image which will work as well.

I hadn't realised the old Jessie image has been retired since I checked over the summer.
As far as I'm aware the newer one should work too.

(Sorry it took so long to get back to you).

**Comment by indigo-** [comment]
Hi!
Is it possible to clone the AMI into the Ireland availability region?
For some reason my account isn't allowed to create GPU instances- I've had to ask them to increase the limit, and they have, but it only applies to Ireland. I've asked them to do the same for N. Virginia but it took them a few days last time so I'm not expecting a reply anytime soon...
