### ISSUE TITLE
test_opencl Segmentation fault

### ISSUE THREAD

**Issue by anferbui** [HPCE/hpce-2017-cw3#4]
Hi,

When running test_opencl I get a Segmentation fault. I am using AWS and have installed all packages suggested in aws_setup.md.

I ran cmake and make, and when I try to run test_opencl the only output I get 'Segmentation fault'. The offending line seems to be
cl::Platform::get(&platforms);

Any ideas?

**Comment by aaronsheah** [comment]
I had the same problem as well. using AWS, couldn't find `HPCE-2015-GPU-Image` used `HPCE-2014-GPU-Image` instead

**Comment by raymond-williams** [comment]
I also had a Segmentation fault when running on Ubuntu. @m8pple investigated this and found that CMakeLists.txt specifies linking against the (non-existent) Cygwin libraries rather than those of my own OpenCL installation. This was fixed by modifying the address of the library in the `UNIX` case to the location of my own installation. The attached file works for me (you may need to adapt the location).
[CMakeLists.txt](https://github.com/HPCE/hpce-2015-cw4/files/33124/CMakeLists.txt)

**Comment by aaronsheah** [comment]
thanks @raymond-williams, works for me

**Comment by anferbui** [comment]
Works for me too, thanks @raymond-williams

**Comment by mattdouthwaite** [comment]
I had to use {PATH TO THIS FILE}/libOpenCL.so.1 
Not sure if that is an issue or not but the test program works so thought I'd post in case anyone else is struggling with just libOpenCL.so
