### ISSUE TITLE
Issue with git

### ISSUE THREAD

**Issue by mdhchan** [HPCE/hpce-2017-cw3#46]
I ran into a problem while trying to push the repository to my private repo.  It gave the error "repository 'https://github.com/HPCE/hpce-2017-cw3-[YOUR LOGIN]/' not found".  Does anyone else have this same issue?

**Comment by guigzzz** [comment]
Yeah I had this issue as well, it seems like there's an issue sometimes where you only get read access to your private repo. The teacher should fix it next time he's online
![image](https://user-images.githubusercontent.com/16688938/32059024-c8a66a3e-ba62-11e7-90d6-2f21b2b77768.png)

**Comment by mdhchan** [comment]
@guigzzz Thanks for the reply!

**Comment by m8pple** [comment]
Yes @guigzzz is correct, it was the same problem - should be fixed now for @mdhchan .

I've still got no clue why it does it, as I added in some logic to
my scripts to read back the permissions after they were created,
and they claim they are correct.

**Comment by filangelos** [comment]
@m8pple I am also having read-only access to my private repo!

**Comment by m0zjo-code** [comment]
@m8pple I am also having the same issue :(

**Comment by jeg114** [comment]
@m8pple I am having the same issue, here are some screenshots for other people that might run into the error. 

How the repo was cloned without problems but could not be pushed to

![clone](https://user-images.githubusercontent.com/11044493/32142911-4a257c70-bc99-11e7-8a2f-6fceb8497836.JPG)

and how I was correctly authenticated:

![auth](https://user-images.githubusercontent.com/11044493/32142914-56fee3e6-bc99-11e7-9ab0-ca207f40709e.JPG)

**Comment by m0zjo-code** [comment]
@filangel @jeg114 Do you have write access yet? I'm still locked out :'(

**Comment by jeg114** [comment]
nope, if you're using you're student email you can get free private repos anyway, and can use that meanwhile as upstream

**Comment by m8pple** [comment]
I've written a script that goes through every repository and just sets everyone's access
to push, and run it a bunch of times. It seems there is a small probability of failure for
each attempt to set permissions, so I figure by running it a number of times it must
eventually do everyone.

I checked the people posting here, and it seems to have fixed permissions. Still got no idea
what the underlying cause is, as I can't see any problems reported against the github API.

I'll do the same for the cw4 repos as well, as there will be the same thing happening too.
