### ISSUE TITLE
I do not have permission to push to my repository

### ISSUE THREAD

**Issue by ms4917** [HPCE/hpce-2017-cw3#60]
When I am trying to push to my repository I get this error, “Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository.”

**Comment by m8pple** [comment]
You definitely have write permissions to the repo, as you seem to have
pushed something 2 hours ago - though just a readme. So I think you're
encountering some other problem with authentication. How is the "remote"
configured in your local ssh client? Are you using `https` or `ssh`? If it
is `ssh`, then you should check whether you can actually ssh to github:
```
ssh git@github.com
````
and check that you can authenticate.

It's also worth checking that you are trying to push to the correct remote - you
might accidentally be trying to push back to `hpce-2017-cw3`, which you shouldn't
have access to.

I also notice that you've put a readme in your repo, rather than cloning from the
master repo, which may cause problems when you try to push (though not the
problem above). One way round this will be to "force push" your local repository
up to the remote - just make _very_ sure you are pushing to the correct remote.

**Comment by m8pple** [comment]
Looks like this is resolved.
