### ISSUE TITLE
Can you start to autotest earlier?

### ISSUE THREAD

**Issue by giuliojiang** [HPCE/hpce-2017-cw3#66]
Due to my own time management methods I would prefer not to come back to the cw in the last 3 days before its deadline, so if you could constantly autotest during the whole duration of each assessment, that would help me a lot. I almost missed the autotest for this one.

Or... allow us to run the full tests locally?

**Comment by m8pple** [comment]
( BTW, I'm writing this as the "autotests" run - luxuriate in the overly long answer
to something that could have used a far shorter answer :) )

I'm afraid that "autotests" is more an aspiration than reality. Every auto-test requires
me to sit in front of a terminal for the beginning and the end of the run (though I
may go away in-between, when the tests can't actively break anything).

Full and robust automation would be nice, but I'm nowhere close to an SRE,
and it would be professionally negligent to set up something in a chron job
if I thought it might wipe out peoples repos, to say nothing of the potential
legal negligence issues. Adding robust error handling could be done, but
would make the whole process much more complex - I tried to roughly
estimate the cost of doing that over the summer, and after about 20 hours
prototyping (I spent quite a few mornings in Hyde Park with my laptop
on this when it was sunny) figured it would require about 100+ hours in
order to do a  full push-button CI-style solution that I actually had confidence in.
It's a lot more complex than standard CI, due to the number of users, the potential
failure modes, the number of repositories, the privacy requirements,
the auditing requirements, the potential to lose a tonne of money on AWS,
me not having done it before,  and so on.

I'm sure that off-the-shelf solutions exist, and there are even examples of
this in other universities, and even in-house. DoC has a lot of good automation,
but my general impression has been that these are things involving fewer
moving parts, and these are mostly setup/supported by teaching fellows or support
staff when they work well. For research academics there is always a
balance between time spent teaching, time spent on research, and time
spent on management; for example, this course is much less than 1/3 of
my nominal total personal teaching load, so there is a balance between
how much time is invested here, versus everywhere else. For personal/ethical reasons
I'm against using PhD students as bulk labour (though they can be very effective in other
teaching roles), so choose not to use them for things like automation/marking - I think
they should be doing research, not doing rote work/marking that academics would
prefer not to do.

So having established that I'm:
- Not a competent SRE
- Don't want to use PhD students
we are left with the current situation, which is that the tests get run when
I happen to be in front of a computer and am able to do things. In term time
this tends to be infrequent, as there are many unplanned/unexpected
meetings/interruptions/courseworks-mis-submissions. So the only time
that I could actually _definitely_ commit to running this stuff would be Tuesday morning.
Apart from that, every other day/time is contingent. So the current approach
is trying to balance the desire to give reasonably frequent runs over the period
when most people care about it, versus predictability of runs.

That then brings us to the idea of allowing people to run things locally,
which is what we had with CW1. I'd far prefer to give people the opportunity
to run locally, and spent quite a lot of time trying to set this up this year,
but was ultimately blocked by the following:
- It is very difficult to make things work on all platforms, especially when GPUs
  are involved.
- Any performance relative measurements become impossible to judge.
- Trying to fix the platform doesn't work, as people want to run it on the
  platform they have, and so will do so regardless.

Over the summer I decided the best solution is to somehow finger-print
the environment, so the assessment script would only run if it was in the
exact environment stated (not just tools/OS - also the hardware). But then
I ran out of time :)

In previous years people have asked to have the CW1-CW4 test scripts
(which are not secret in any real sense, just obscure), so I've released
them - then people spend effort and time trying to run them, which isn't
really the point (though may have educational value).

So I'm entirely willing to throw the test scripts over the fence (as it were),
with the explicit statement that they are unsupported, and no questions
will be answered about how to run them. I'll see if I can set a repo up tomorrow,
but it won't happen till the afternoon I'm afraid (they were actually
available for a while under an accidentally readable repo, which was only
intended to be private because of this running/env issue).

-

So, assuming anyone reads this far, a natural question is why I've
spent so long responding to this. On one level, it's because it is
a good/reasonable/common question, and so deserves a reasonably
complete answer. On another level, my train back from a day-long
project meeting in U o Southampton was delayed significantly by
trespassers on the line. But also because it comes back to tradeoffs
and metrics - there is a clear tension between the virtuous students
(getting CW done ahead of time), the last-minuters (can you do a run
at 19:00 on Fri?). This could be addressed by decreasing latency or increasing
rate (not the same thing...), but there are a lot of secondary costs there.
Design time, execution time, robustness, cost, security, ....

**Comment by m8pple** [comment]
So I put all the scripts in this repository:
https://github.com/HPCE/hpce-2017-unsupported-scripts

It is basically the same as the private repository, but with some other junk stripped out.

@filangel was asking about these as well, so tagging them in.

**Comment by giuliojiang** [comment]
Thanks for publishing the scripts. Much appreciated!
