### ISSUE TITLE
OpenCL Version taking longer to run than software 

### ISSUE THREAD

**Issue by bngzl** [HPCE/hpce-2017-cw3#67]
I ran the final test scripts as required: 
time (bin/make_world 5000 0.1 1 | bin/step_world 0.1 1000 1 > /dev/null)
time (bin/make_world 5000 0.1 1 | bin/bn514/step_world_v3_opencl 0.1 1000 1 > /dev/null)
time (bin/make_world 5000 0.1 1 | bin/bn514/step_world_v4_double_buffered 0.1 1000 1 > /dev/null)
time (bin/make_world 5000 0.1 1 | bin/bn514/step_world_v5_packed_properties 0.1 1000 1 > /dev/null)

But my results are unexpected in that: 
1) OpenCL version (v3) takes longer (3m 8.820s) than software (2m 21s) 
2) v5 (24.8s) isn't very much faster than v4 (25.5s) 

Are there any specific reasons for such results? I would expect the openCL version to take longer for small worlds and relatively small time steps (i.e n=10) but at n=1000 i would expect the transfer overheads to be worth it. 

Thank you!

**Comment by m8pple** [comment]
It's not clear what platform you're running under here. Is this under AWS?

Using w=256, h=256, n=10000, I get something closer to:
- Software = 8.8s
- V3 = 2.5s
- V4 = 0.55s
- V5 = 0.49s

So about an 18x speedup from start to end. I'm not choosing
problems that will give spectacular speedups here, the goal is to
be realistic, but you should be seeing a boost.

If you're using a laptop or weak integrated desktop GPU then you may
well see slower performance though - GPUs are not a panacea, and there
is no guarantee that you will see higher performance for any given platform.

**Comment by bngzl** [comment]
Sorry I forgot to specify the platform and hardware I was using! 

My laptop has dualcore i7 processor with a NVIDIA 730M graphics card, running ubuntu 16.04. 
Curiously, under different n, my v3 does run faster than software, but not to a very large extent. 

I've checked all the output and they're all correct and my code passes all 28 of your test logs. (Does that mean everything is correct?) I suppose it could be due to hardware issues? Perhaps attempting them on AWS should solve this discrepancy.

**Comment by ppp2211** [comment]
The ratios of speedup you see vary **hugely** depending on the platform you use. 

As an example, on my laptop (i5-4310U + Intel HD4400 with shared memory), for 5000x5000 world and 1000 steps  I get:
* Soft = 2m10s (1x)
* V3 = 1m16s (1.7x)
* V5 = 36.2s (3.59x)

Which is a decent speedup, but not huge by any margin. Slow-ish CPU and a slow GPU - however the GPU doesn't have any dedicated memory, so the penalty for swapping in and out of RAM isn't huge (as it's all in the same memory anyway), and so V5 is only mildly faster than V3.

However, using an i7-4790k + GTX1080:
* Soft = 1m21s (1x)
* V3 = 39.97s (2.02x)
* V5 = 1.71s (47.3x)

So the V3 result is completely garbage if you consider that the 1080 has (in theory) 2048 cores, and it's barely 2x faster than a quad-core i7... but when you optimize the code, it gets close to 50x.

Now if you have a smaller GPU core but with dedicated GPU memory (which you do - 730M has 384 cores with 2-4GB of its own DDR3), V3 may as well be worse than software - because the penalty associated with you constantly reading/writing from GPU memory will be higher than what you gained by running the compute on a GPU.

**Comment by bngzl** [comment]
I see! Thanks for the explanation (:
