### ISSUE TITLE
Mingw64-time

### ISSUE THREAD

**Issue by wh1114** [HPCE/hpce-2017-cw3#69]
Dear all,

The mingw64-time from cw1 for canned version would not run when have two bin files running like 
`bin/mingw64-time.exe (bin/make_world | bin/step_world 0.1 1 > /dev/null)`

Would it be possible to ammend the time function so as to time the kernel on mingw?

Thank you.

**Comment by wh1114** [comment]
I was able to run it like 
`bin/mingw64-time.exe bin/make_world | bin/mingw64-time.exe bin/step_world 0.1 1 > /dev/null
`

and add two numbers together, but I would be quiet a mass if multiple programme is running together.

Thank you

**Comment by wh1114** [comment]
I was able to run it like
`bin/mingw64-time.exe bin/make_world | bin/mingw64-time.exe bin/step_world 0.1 1 > /dev/null`

and add two numbers together, but it would be quiet a mass if multiple programme is running together.

Thank you

**Comment by m8pple** [comment]
I'm afraid that modifying the custom `mingw64-time` to support compound
commands would be a significant problem.

However, I believe that the builtin mingw `time` works ok for wall-clock time, and
that should support compound commands. It's only total CPU time that you don't
get, which is not so relevant here.

So (without trying it out), I would guess that:
```
time ( bin/make_world | bin/mingw64-time.exe bin/step_world 0.1 1 > /dev/null )
```
does give you correct wall-clock time, even if the total CPU time is not correct?

**Comment by wh1114** [comment]
I see, the time I got while running the code is as followed.
![image](https://user-images.githubusercontent.com/32774520/32301408-b7c09260-bf55-11e7-9071-60cd276725a9.png)
I tried running this 
![image](https://user-images.githubusercontent.com/32774520/32302035-89ffe44a-bf58-11e7-8062-53a3c39bbb46.png)
The measurement made by time function is still off by a bit in comparison to mingw64-time.
However, if the iteration takes a long time, the minor difference would not make a huge difference
![image](https://user-images.githubusercontent.com/32774520/32302101-defe6c6e-bf58-11e7-8cf7-a576a7f6ca24.png)
Thank you very much for the reply

**Comment by m8pple** [comment]
Notice that your mingw-time and bash time are not actually measuring the same thing.
So for this command:
```
time ( bin/make_world | bin/mingw64-time.exe bin/step_world 0.1 1 > /dev/null )
```
we are actually capturing two times:
- 0.187 secs for `bin/mingw64-time.exe bin/step_world 0.1 1`
- 0.337 secs for `time ( the-whole-thing )`

The time of the first is contained within the time of the second, plus there is the
additional overhead of launching `bin/make_world` and `bin/mingw64-time`
(which is not free). So that delta of 0.15 secs is roughly the cost of creating
the sub-shell (the part in parenthesis) plus setting up the pipeline and launching
`bin/make_world` and `bin/mingw64-time`.

Notice that in the final results you still see a delta of about 0.15 secs, as that
overhead is roughly constant, but the other cost is variable.
