### ISSUE TITLE
precision tests failure

### ISSUE THREAD

**Issue by filangelos** [HPCE/hpce-2017-cw3#71]
Could you please provide us with the testing framework, since I am having trouble with tests 22-26 due to `MISMATCH`ed values. This would help us debug it, instead of waiting one test run per day!

**Comment by m8pple** [comment]
I've provided the scripts elsewhere (see #66 ), but actually all the information you
need is available in the logs.

You're interpreting it as a precision problem, but that is not really likely here, and there is
sufficient information in the logs to guide you towards it if you dig a bit.

My guess is that this is a testing problem.

For example, a very common output to see is (I'm grabbing it from the
`dt10_logs/2017-11-01--22-15/log/test_22.log` file in your repo, but others
have similar results):
```
Loaded world with w=64, h=64
Stepping by dt=0.1 for n=1
Loaded world with w=64, h=64
Stepping by dt=0.1 for n=1
Found 2 platforms
  Platform 0 : NVIDIA Corporation
  Platform 1 : Advanced Micro Devices, Inc.
Choosing platform 0
Found 1 devices
  Device 0 : GRID K520
Choosing device 0
Loaded world under test from stdin with w=64, h=64
Loaded expected world from file '/dev/fd/63' with w=64, h=64
MISMATCH: Worlds have different state at x=1, y=2 : got 0, expected 0.344086
MISMATCH: Worlds have different state at x=2, y=2 : got 0, expected 0.256
MISMATCH: Worlds have different state at x=3, y=2 : got 0, expected 0.256
MISMATCH: Worlds have different state at x=4, y=2 : got 0, expected 0.256
MISMATCH: Worlds have different state at x=5, y=2 : got 0, expected 0.256
MISMATCH: Worlds have different state at x=6, y=2 : got 0, expected 0.256
MISMATCH: Worlds have different state at x=7, y=2 : got 0, expected 0.256
MISMATCH: Worlds have different state at x=8, y=2 : got 0, expected 0.256
MISMATCH: Worlds have different state at x=9, y=2 : got 0, expected 0.256
MISMATCH: Worlds have different state at x=10, y=2 : got 0, expected 0.256
MISMATCH: Worlds have different state at x=11, y=2 : got 0, expected 0.256
  Eliding remaining property mismatches.
```
This tells us that:
- w=64, h=64 : So quite a small world.
- dt = 0.1 : So a very normal step (neither small nor big)
- n = 1 : That seems like an interesting number - it is as small as seems reasonable, and is very testable.
- We're getting out values of got = 0. Those seem _very_ interesting, as values of 0 tend to be
  associated with default or reset values.

Looking at the command given in the log (`dt10_logs/2017-11-01--22-15/xxxx.log`) for that test,
we have the command (with prefixes stripped out):
```
(cd
    ./tmp/xxxx/working && scripts/src/make_world 64 64
    |
    ./step_world_v4_double_buffered |
    scripts/src/compare_worlds   <(scripts/src/make_world 64 64 | scripts/src/step_world ))
    &> ./tmp/xxxx/log/test_22.log
```
So essentially it is comparing the output of:
- step_world_v4_double_buffered with no parameters
- step_world with no parameters
on a world size of 64x64.

So this is just the default world size, tested with the default parameters. It should
be possible to replicate that locally, and ideally would probably have been part of your
functional testing flow. My first step would be to just eyeball the textual output
of the double buffered version and the plain version - are they the same?

It's quite common for people to want to test on large n, because then they see
the performance gains, but a lot of the _functional_ testing should happen for
small (or smallest) n. When this problem occurs for large n it looks superficially
like a floating-point precision problem, but actually the errors are too high.

So my suspicion is that this is an iterative testing problem. In general optimisation
should be progressive, and there should be functional testing to ensure that
each optimisation still results in the same functional behaviour.

**Comment by filangelos** [comment]
Thank you for the new `unsupported-scripts` repo! The title of the issue was probably misleading, I understood that there was a functional error, that's why I requested the tests in order to debug it more easily!<br><br>

I would be happy to close the issue, but please @m8pple decide when is best to do, since other students may be interested in the new repo!

**Comment by m8pple** [comment]
Yes, I'll leave it here for a while, as others might be interested in the discussion too
(that's why it's great when people do post issues about this sort of thing, as it is 
often a chance to discuss a problem that I know multiple people might have).
