### ISSUE TITLE
Final test failure

### ISSUE THREAD

**Issue by paulbalaji** [HPCE/hpce-2017-cw3#72]
so my final test says:

> pmb14, 27, For n=256, steps=2048: Check time for v4 (0.39) is more than 1.01 (updated) x v5 (0.39), FAIL

so 0.39 is not 1.01x 0.39 but in a previous run, it passed because it was comparing 0.39 and 0.38

so do I just hope that the v5 time rounds to 0.38 next time?

**Comment by m8pple** [comment]
In essence, yes - you're right in your analysis of what is happening. So waiting and seeing
what happens in the final run is certainly one approach (probably even a good approach).

It is intentionally on the edge for the AWS GPU, as the packing only makes things marginally
faster _on this particular platform_ (for other platforms it works quite well), but it is more
likely than not for it to pass. So it adds some random sizzle on the results, introducing a
standard-deviation of about 0.5% to the results. However, you're not required
to stop optimising as soon as the packing is done (some people add more optimisations
without thinking about it, and so won't see this behaviour).

An outcome of the course is an understanding of the inherent difficulty in measuring results,
but also that there is a tradeof between design effort/time and achieved performance.
It is possible to change the kernel to make passing the test close to a certainty (although
it is never 100% certain), though it depends how much effort one is willing to spend,
versus the benefit of moving the average expected mark up by 1.9% to 100%.

Philosophically, I've always been quite happy with having this behaviour, though I
tweaked it a bit in order to make it a bit more biased towards passing a while back.
See for example #38, #32, where this came up before, where the test was more severe.

**Comment by al2114** [comment]
I have found the same problem. However, due to the dependency relationship between the various tests, does that not mean having a sub-optimal passing v4 optimises for the success of v5 indicating the test to be fundamentally flawed?
